### ISSUE TITLE
Uncaught (in promise) Error: session not initialized yet

### ISSUE THREAD

**Issue by huanghaiyang** [githubharald/githubharald.github.io#1]
session.ts:103 Uncaught (in promise) Error: session not initialized yet
    at e.run (session.ts:103:13)
    at t.<anonymous> (inference-session-impl.ts:56:35)
    at onnx.min.js:14:252919
    at Object.next (onnx.min.js:14:253024)
    at onnx.min.js:14:251936
    at new Promise (<anonymous>)
    at a (onnx.min.js:14:251681)
    at t.run (onnx.min.js:14:253610)
    at infer (script.js:65:32)
    at HTMLButtonElement.onclick (text_reader.html:47:35)

**Comment by githubharald** [comment]
did you get it working?

**Comment by huanghaiyang** [comment]
> did you get it working?

yes
